#!/bin/bash 

~/.fehbg &
picom --config ~/.config/openbox/picom/picom.conf --experimental-backends &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
tint2 &
dunst &
redshift &
flameshot &
nm-applet &

